# Generated by Django 5.2.12 on 2026-04-06 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('secteur_activite', models.CharField(help_text='Ex: Énergie / Hydrocarbures, Informatique, Commerce...', max_length=100)),
                ('registre_commerce', models.CharField(max_length=50, unique=True, verbose_name='Numéro de Registre de Commerce (RC)')),
                ('wilaya_siege', models.CharField(max_length=50, verbose_name='Wilaya du siège social')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Présentation de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_entreprises/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('wilaya', models.CharField(max_length=50, verbose_name='Lieu de travail (Wilaya)')),
                ('missions', models.TextField(verbose_name='Missions du poste')),
                ('profil_recherche', models.TextField(verbose_name='Profil recherché (Exigences)')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('ANEM', 'Contrat ANEM (CTA / DAIP)'), ('STAGE', 'Stage / PFE'), ('FREELANCE', 'Freelance')], default='CDI', max_length=20)),
                ('experience_requise', models.CharField(choices=[('DEBUTANT', 'Débutant (0 - 1 an)'), ('JUNIOR', 'Junior (1 - 3 ans)'), ('CONFIRME', 'Confirmé (3 - 5 ans)'), ('SENIOR', 'Senior (5 ans et plus)')], default='DEBUTANT', max_length=20)),
                ('salaire_propose', models.CharField(blank=True, help_text="Ex: 68 000 DA Net, ou 'À négocier'", max_length=100, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True, verbose_name='Offre visible')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='jobs.profilentreprise')),
            ],
        ),
    ]
