# Generated by Django 5.2.12 on 2026-04-07 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('lettre_motivation', models.TextField(blank=True, null=True, verbose_name='Lettre de motivation (Optionnelle)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'examen"), ('EXAMINEE', 'Candidature examinée'), ('ACCEPTEE', 'Retenu pour entretien'), ('REFUSEE', 'Candidature refusée')], default='EN_ATTENTE', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='jobs.offreemploi')),
            ],
            options={
                'unique_together': {('offre', 'candidat')},
            },
        ),
    ]
