# Generated by Django 5.2.12 on 2026-04-09 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_candidature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_professionnel', models.CharField(blank=True, max_length=150, null=True)),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_candidat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
