# Generated by Django 5.2.12 on 2026-04-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_profilcandidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='est_approuvee',
            field=models.BooleanField(default=False, verbose_name='Entreprise approuvée'),
        ),
    ]
