# Generated by Django 5.2.12 on 2026-04-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_profilentreprise_est_approuvee'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='missions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='profil_recherche',
            field=models.TextField(blank=True, null=True),
        ),
    ]
