# Generated by Django 5.2.12 on 2026-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_offreemploi_description_alter_offreemploi_missions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description générale'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='missions',
            field=models.TextField(blank=True, null=True, verbose_name='Missions du poste'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='profil_recherche',
            field=models.TextField(blank=True, null=True, verbose_name='Profil recherché (Exigences)'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='salaire_propose',
            field=models.CharField(blank=True, help_text='Ex: 68 000 DA Net', max_length=100, null=True),
        ),
    ]
