# Generated by Django 5.2.12 on 2026-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_offreemploi_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
