# Generated by Django 5.2.12 on 2026-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_profilcandidat_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='competences',
            field=models.TextField(blank=True, null=True, verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='diplome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diplôme'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='experiences',
            field=models.TextField(blank=True, null=True, verbose_name='Expériences'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='langues',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Langues'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='specialite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Spécialité'),
        ),
    ]
