# Generated by Django 5.2.12 on 2026-04-10 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_profilcandidat_competences_profilcandidat_diplome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilcandidat',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
