# Generated by Django 5.2.12 on 2026-04-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_profilcandidat_cv_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='diplome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diplôme requis'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='specialite',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Spécialité'),
        ),
    ]
