# Generated by Django 5.2.12 on 2026-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_offreemploi_commune_offreemploi_diplome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='statut_moderation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('APPROUVEE', 'Approuvée et en ligne'), ('REJETEE', 'Rejetée (à corriger)')], default='EN_ATTENTE', max_length=20),
        ),
    ]
