# Generated by Django 5.2.12 on 2026-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_offreemploi_motif_rejet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='diplome',
            field=models.CharField(blank=True, choices=[('NIVEAU_SECONDAIRE', 'Niveau Secondaire'), ('NIVEAU_TERMINAL', 'Niveau Terminal'), ('BACCALAUREAT', 'Baccalauréat'), ('TS', 'TS Bac +2'), ('LICENCE', 'Licence (LMD), Bac + 3'), ('MASTER_1', 'Master 1, Licence Bac + 4'), ('MASTER_2', 'Master 2, Ingéniorat, Bac + 5'), ('MAGISTERE', 'Magistère Bac + 7'), ('DOCTORAT', 'Doctorat'), ('NON_DIPLOMANTE', 'Non Diplômante'), ('FORMATION_PRO', 'Formation Professionnelle'), ('UNIVERSITAIRE_SANS_DIPLOME', 'Universitaire Sans Diplôme'), ('CERTIFICATION', 'Certification')], max_length=100, null=True, verbose_name='Diplôme requis'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='experience_requise',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant / Junior'), ('JEUNE_DIPLOME', 'Jeune Diplômé'), ('STAGIAIRE', 'Stagiaire / Etudiant'), ('CONFIRME', 'Confirmé / Expérimenté'), ('MANAGER', 'Manager / Responsable Département'), ('RESPONSABLE_EQUIPE', "Responsable d'Équipe"), ('CADRE_DIRIGEANT', 'Cadre Dirigeant')], default='DEBUTANT', max_length=50),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='specialite',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('BANQUE', 'Métiers Banque et Assurances'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True, verbose_name='Spécialité / Secteur'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('ANEM', 'Contrat ANEM (CTA / DAIP)'), ('STAGE', 'Stage / PFE'), ('FREELANCE', 'Freelance'), ('TEMPS_PARTIEL', 'Temps Partiel')], default='CDI', max_length=50),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='wilaya',
            field=models.CharField(choices=[('01 - Adrar', '01 - Adrar'), ('02 - Chlef', '02 - Chlef'), ('03 - Laghouat', '03 - Laghouat'), ('04 - Oum El Bouaghi', '04 - Oum El Bouaghi'), ('05 - Batna', '05 - Batna'), ('06 - Béjaïa', '06 - Béjaïa'), ('07 - Biskra', '07 - Biskra'), ('08 - Béchar', '08 - Béchar'), ('09 - Blida', '09 - Blida'), ('10 - Bouira', '10 - Bouira'), ('11 - Tamanrasset', '11 - Tamanrasset'), ('12 - Tébessa', '12 - Tébessa'), ('13 - Tlemcen', '13 - Tlemcen'), ('14 - Tiaret', '14 - Tiaret'), ('15 - Tizi Ouzou', '15 - Tizi Ouzou'), ('16 - Alger', '16 - Alger'), ('17 - Djelfa', '17 - Djelfa'), ('18 - Jijel', '18 - Jijel'), ('19 - Sétif', '19 - Sétif'), ('20 - Saïda', '20 - Saïda'), ('21 - Skikda', '21 - Skikda'), ('22 - Sidi Bel Abbès', '22 - Sidi Bel Abbès'), ('23 - Annaba', '23 - Annaba'), ('24 - Guelma', '24 - Guelma'), ('25 - Constantine', '25 - Constantine'), ('26 - Médéa', '26 - Médéa'), ('27 - Mostaganem', '27 - Mostaganem'), ("28 - M'Sila", "28 - M'Sila"), ('29 - Mascara', '29 - Mascara'), ('30 - Ouargla', '30 - Ouargla'), ('31 - Oran', '31 - Oran'), ('32 - El Bayadh', '32 - El Bayadh'), ('33 - Illizi', '33 - Illizi'), ('34 - Bordj Bou Arréridj', '34 - Bordj Bou Arréridj'), ('35 - Boumerdès', '35 - Boumerdès'), ('36 - El Tarf', '36 - El Tarf'), ('37 - Tindouf', '37 - Tindouf'), ('38 - Tissemsilt', '38 - Tissemsilt'), ('39 - El Oued', '39 - El Oued'), ('40 - Khenchela', '40 - Khenchela'), ('41 - Souk Ahras', '41 - Souk Ahras'), ('42 - Tipaza', '42 - Tipaza'), ('43 - Mila', '43 - Mila'), ('44 - Aïn Defla', '44 - Aïn Defla'), ('45 - Naâma', '45 - Naâma'), ('46 - Aïn Témouchent', '46 - Aïn Témouchent'), ('47 - Ghardaïa', '47 - Ghardaïa'), ('48 - Relizane', '48 - Relizane'), ('49 - Timimoun', '49 - Timimoun'), ('50 - Bordj Badji Mokhtar', '50 - Bordj Badji Mokhtar'), ('51 - Ouled Djellal', '51 - Ouled Djellal'), ('52 - Béni Abbès', '52 - Béni Abbès'), ('53 - In Salah', '53 - In Salah'), ('54 - In Guezzam', '54 - In Guezzam'), ('55 - Touggourt', '55 - Touggourt'), ('56 - Djanet', '56 - Djanet'), ("57 - El M'Ghair", "57 - El M'Ghair"), ('58 - El Meniaa', '58 - El Meniaa')], max_length=100, verbose_name='Lieu de travail (Wilaya)'),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='diplome',
            field=models.CharField(blank=True, choices=[('NIVEAU_SECONDAIRE', 'Niveau Secondaire'), ('NIVEAU_TERMINAL', 'Niveau Terminal'), ('BACCALAUREAT', 'Baccalauréat'), ('TS', 'TS Bac +2'), ('LICENCE', 'Licence (LMD), Bac + 3'), ('MASTER_1', 'Master 1, Licence Bac + 4'), ('MASTER_2', 'Master 2, Ingéniorat, Bac + 5'), ('MAGISTERE', 'Magistère Bac + 7'), ('DOCTORAT', 'Doctorat'), ('NON_DIPLOMANTE', 'Non Diplômante'), ('FORMATION_PRO', 'Formation Professionnelle'), ('UNIVERSITAIRE_SANS_DIPLOME', 'Universitaire Sans Diplôme'), ('CERTIFICATION', 'Certification')], max_length=100, null=True, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='specialite',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('BANQUE', 'Métiers Banque et Assurances'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True, verbose_name='Spécialité / Secteur'),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='secteur_activite',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('BANQUE', 'Métiers Banque et Assurances'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='wilaya_siege',
            field=models.CharField(choices=[('01 - Adrar', '01 - Adrar'), ('02 - Chlef', '02 - Chlef'), ('03 - Laghouat', '03 - Laghouat'), ('04 - Oum El Bouaghi', '04 - Oum El Bouaghi'), ('05 - Batna', '05 - Batna'), ('06 - Béjaïa', '06 - Béjaïa'), ('07 - Biskra', '07 - Biskra'), ('08 - Béchar', '08 - Béchar'), ('09 - Blida', '09 - Blida'), ('10 - Bouira', '10 - Bouira'), ('11 - Tamanrasset', '11 - Tamanrasset'), ('12 - Tébessa', '12 - Tébessa'), ('13 - Tlemcen', '13 - Tlemcen'), ('14 - Tiaret', '14 - Tiaret'), ('15 - Tizi Ouzou', '15 - Tizi Ouzou'), ('16 - Alger', '16 - Alger'), ('17 - Djelfa', '17 - Djelfa'), ('18 - Jijel', '18 - Jijel'), ('19 - Sétif', '19 - Sétif'), ('20 - Saïda', '20 - Saïda'), ('21 - Skikda', '21 - Skikda'), ('22 - Sidi Bel Abbès', '22 - Sidi Bel Abbès'), ('23 - Annaba', '23 - Annaba'), ('24 - Guelma', '24 - Guelma'), ('25 - Constantine', '25 - Constantine'), ('26 - Médéa', '26 - Médéa'), ('27 - Mostaganem', '27 - Mostaganem'), ("28 - M'Sila", "28 - M'Sila"), ('29 - Mascara', '29 - Mascara'), ('30 - Ouargla', '30 - Ouargla'), ('31 - Oran', '31 - Oran'), ('32 - El Bayadh', '32 - El Bayadh'), ('33 - Illizi', '33 - Illizi'), ('34 - Bordj Bou Arréridj', '34 - Bordj Bou Arréridj'), ('35 - Boumerdès', '35 - Boumerdès'), ('36 - El Tarf', '36 - El Tarf'), ('37 - Tindouf', '37 - Tindouf'), ('38 - Tissemsilt', '38 - Tissemsilt'), ('39 - El Oued', '39 - El Oued'), ('40 - Khenchela', '40 - Khenchela'), ('41 - Souk Ahras', '41 - Souk Ahras'), ('42 - Tipaza', '42 - Tipaza'), ('43 - Mila', '43 - Mila'), ('44 - Aïn Defla', '44 - Aïn Defla'), ('45 - Naâma', '45 - Naâma'), ('46 - Aïn Témouchent', '46 - Aïn Témouchent'), ('47 - Ghardaïa', '47 - Ghardaïa'), ('48 - Relizane', '48 - Relizane'), ('49 - Timimoun', '49 - Timimoun'), ('50 - Bordj Badji Mokhtar', '50 - Bordj Badji Mokhtar'), ('51 - Ouled Djellal', '51 - Ouled Djellal'), ('52 - Béni Abbès', '52 - Béni Abbès'), ('53 - In Salah', '53 - In Salah'), ('54 - In Guezzam', '54 - In Guezzam'), ('55 - Touggourt', '55 - Touggourt'), ('56 - Djanet', '56 - Djanet'), ("57 - El M'Ghair", "57 - El M'Ghair"), ('58 - El Meniaa', '58 - El Meniaa')], max_length=100, verbose_name='Wilaya du siège social'),
        ),
    ]
