# Generated by Django 5.2.12 on 2026-04-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_offreemploi_diplome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_poste', models.CharField(max_length=200, verbose_name='Titre du poste (Ex: Développeur Front-End)')),
                ('entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (Vide si toujours en poste)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Missions et réalisations')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_detail', to='jobs.profilcandidat')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FormationCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=200, verbose_name='Nom de la formation ou diplôme')),
                ('etablissement', models.CharField(max_length=200, verbose_name='Université ou École')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description ou mention')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_detail', to='jobs.profilcandidat')),
            ],
            options={
                'ordering': ['-date_fin'],
            },
        ),
    ]
