# Generated by Django 5.2.12 on 2026-04-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_experiencecandidat_formationcandidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
