# Generated by Django 5.2.12 on 2026-04-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_profilcandidat_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='mobilite',
            field=models.CharField(blank=True, choices=[('LOCALE', 'Locale (Wilaya)'), ('REGIONALE', 'Régionale'), ('NATIONALE', 'Nationale'), ('INTERNATIONALE', 'Internationale')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='passeport_valide',
            field=models.BooleanField(default=False, verbose_name='Passeport valide'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='permis_conduire',
            field=models.BooleanField(default=False, verbose_name='Permis de conduire'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='salaire_souhaite',
            field=models.CharField(blank=True, help_text='Ex: 80 000 DA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='secteur_souhaite',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('BANQUE', 'Métiers Banque et Assurances'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='service_militaire',
            field=models.CharField(blank=True, choices=[('NON_CONCERNE', 'Non concerné (Femme)'), ('DEGAGE', 'Dégagé'), ('SURSITAIRE', 'Sursitaire'), ('INAPTE', 'Inapte'), ('INCORPORE', 'Incorporé')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='situation_actuelle',
            field=models.CharField(blank=True, choices=[('EN_RECHERCHE', 'En recherche active'), ('EN_POSTE', 'En poste'), ('A_L_ECOUTE', "À l'écoute du marché"), ('ETUDIANT', 'Étudiant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='vehicule_personnel',
            field=models.BooleanField(default=False, verbose_name='Véhiculé'),
        ),
    ]
