# Generated by Django 5.2.12 on 2026-04-22 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_profilcandidat_mobilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='lettre_motivation_file',
            field=models.FileField(blank=True, null=True, upload_to='lettres_motivation/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Lettre de motivation (Fichier)'),
        ),
    ]
