# Generated by Django 5.2.12 on 2026-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_candidature_lettre_motivation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='est_cloturee',
            field=models.BooleanField(default=False),
        ),
    ]
