# Generated by Django 5.2.12 on 2026-04-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_offreemploi_est_cloturee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='notif_mise_a_jour',
            field=models.BooleanField(default=True, verbose_name='Emails de mise à jour'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='notif_newsletter',
            field=models.BooleanField(default=True, verbose_name='Actualités et newsletter'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='notif_offres_exclusives',
            field=models.BooleanField(default=True, verbose_name='Offres exclusives et partenaires'),
        ),
        migrations.CreateModel(
            name='AlerteEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mots_cles', models.CharField(max_length=255, verbose_name='Mots clés')),
                ('wilaya', models.CharField(blank=True, choices=[('01 - Adrar', '01 - Adrar'), ('02 - Chlef', '02 - Chlef'), ('03 - Laghouat', '03 - Laghouat'), ('04 - Oum El Bouaghi', '04 - Oum El Bouaghi'), ('05 - Batna', '05 - Batna'), ('06 - Béjaïa', '06 - Béjaïa'), ('07 - Biskra', '07 - Biskra'), ('08 - Béchar', '08 - Béchar'), ('09 - Blida', '09 - Blida'), ('10 - Bouira', '10 - Bouira'), ('11 - Tamanrasset', '11 - Tamanrasset'), ('12 - Tébessa', '12 - Tébessa'), ('13 - Tlemcen', '13 - Tlemcen'), ('14 - Tiaret', '14 - Tiaret'), ('15 - Tizi Ouzou', '15 - Tizi Ouzou'), ('16 - Alger', '16 - Alger'), ('17 - Djelfa', '17 - Djelfa'), ('18 - Jijel', '18 - Jijel'), ('19 - Sétif', '19 - Sétif'), ('20 - Saïda', '20 - Saïda'), ('21 - Skikda', '21 - Skikda'), ('22 - Sidi Bel Abbès', '22 - Sidi Bel Abbès'), ('23 - Annaba', '23 - Annaba'), ('24 - Guelma', '24 - Guelma'), ('25 - Constantine', '25 - Constantine'), ('26 - Médéa', '26 - Médéa'), ('27 - Mostaganem', '27 - Mostaganem'), ("28 - M'Sila", "28 - M'Sila"), ('29 - Mascara', '29 - Mascara'), ('30 - Ouargla', '30 - Ouargla'), ('31 - Oran', '31 - Oran'), ('32 - El Bayadh', '32 - El Bayadh'), ('33 - Illizi', '33 - Illizi'), ('34 - Bordj Bou Arréridj', '34 - Bordj Bou Arréridj'), ('35 - Boumerdès', '35 - Boumerdès'), ('36 - El Tarf', '36 - El Tarf'), ('37 - Tindouf', '37 - Tindouf'), ('38 - Tissemsilt', '38 - Tissemsilt'), ('39 - El Oued', '39 - El Oued'), ('40 - Khenchela', '40 - Khenchela'), ('41 - Souk Ahras', '41 - Souk Ahras'), ('42 - Tipaza', '42 - Tipaza'), ('43 - Mila', '43 - Mila'), ('44 - Aïn Defla', '44 - Aïn Defla'), ('45 - Naâma', '45 - Naâma'), ('46 - Aïn Témouchent', '46 - Aïn Témouchent'), ('47 - Ghardaïa', '47 - Ghardaïa'), ('48 - Relizane', '48 - Relizane'), ('49 - Timimoun', '49 - Timimoun'), ('50 - Bordj Badji Mokhtar', '50 - Bordj Badji Mokhtar'), ('51 - Ouled Djellal', '51 - Ouled Djellal'), ('52 - Béni Abbès', '52 - Béni Abbès'), ('53 - In Salah', '53 - In Salah'), ('54 - In Guezzam', '54 - In Guezzam'), ('55 - Touggourt', '55 - Touggourt'), ('56 - Djanet', '56 - Djanet'), ("57 - El M'Ghair", "57 - El M'Ghair"), ('58 - El Meniaa', '58 - El Meniaa')], max_length=100, null=True, verbose_name='Région, Wilaya')),
                ('frequence', models.CharField(choices=[('QUOTIDIENNE', 'Quotidienne'), ('HEBDOMADAIRE', 'Hebdomadaire')], default='QUOTIDIENNE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True, verbose_name='Alerte activée')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OffreSauvegardee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sauvegarde', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_sauvegardees', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauvegardee_par', to='jobs.offreemploi')),
            ],
            options={
                'ordering': ['-date_sauvegarde'],
                'unique_together': {('candidat', 'offre')},
            },
        ),
    ]
