# Generated by Django 5.2.12 on 2026-04-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_candidature_score_matching_profilcandidat_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='details_matching',
            field=models.JSONField(blank=True, null=True, verbose_name='Détails du Matching'),
        ),
    ]
