# Generated by Django 5.2.12 on 2026-04-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_candidature_details_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='commune_siege',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Commune du siège'),
        ),
    ]
