# Generated by Django 5.2.12 on 2026-04-29 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_profilentreprise_commune_siege'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidature',
            name='cv_rapide',
            field=models.FileField(blank=True, null=True, upload_to='cv_rapide/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='candidature',
            name='email_rapide',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='est_rapide',
            field=models.BooleanField(default=False, verbose_name='Postulation Rapide'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='nom_rapide',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenom_rapide',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='telephone_rapide',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
