# Generated by Django 5.2.12 on 2026-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_candidature_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'entretien"),
        ),
    ]
