# Generated by Django 5.2.12 on 2026-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_candidature_date_entretien'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='message_entretien',
            field=models.TextField(blank=True, null=True, verbose_name='Message du recruteur'),
        ),
    ]
