# Generated by Django 5.2.12 on 2026-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('INFO', 'Information'), ('ENTRETIEN', 'Entretien programmé'), ('RETENU', 'Candidature retenue'), ('REFUS', 'Candidature refusée'), ('ALERTE', 'Alerte Emploi')], default='INFO', max_length=20),
        ),
    ]
