# Generated by Django 5.2.12 on 2026-05-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_alter_notification_type_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='niveau_experience',
            field=models.CharField(blank=True, choices=[('DEBUTANT', 'Débutant / Junior'), ('JEUNE_DIPLOME', 'Jeune Diplômé'), ('STAGIAIRE', 'Stagiaire / Etudiant'), ('CONFIRME', 'Confirmé / Expérimenté'), ('MANAGER', 'Manager / Responsable Département'), ('RESPONSABLE_EQUIPE', "Responsable d'Équipe"), ('CADRE_DIRIGEANT', 'Cadre Dirigeant')], max_length=50, null=True, verbose_name="Niveau d'expérience global"),
        ),
        migrations.AddField(
            model_name='profilentreprise',
            name='est_premium',
            field=models.BooleanField(default=False, verbose_name='Compte Premium (Accès CVthèque)'),
        ),
    ]
