# Generated by Django 5.2.12 on 2026-05-23 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_candidature_commentaire_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='taille_entreprise',
            field=models.CharField(blank=True, choices=[('TPE', '1 à 10 employés'), ('PE', '11 à 50 employés'), ('ME', '51 à 200 employés'), ('GE', '201 à 500 employés'), ('TGE', 'Plus de 500 employés')], max_length=10, null=True, verbose_name="Taille de l'entreprise (effectif)"),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_entreprises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
