# Generated by Django 5.2.12 on 2026-05-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_profilcandidatfavori'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='email_refus_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilentreprise',
            name='message_refus_auto',
            field=models.TextField(blank=True, default="Bonjour {prenom},\n\nNous avons bien étudié votre candidature pour le poste de {titre_offre} et nous avons le regret de vous informer qu'elle n'a pas été retenue.\n\nNous vous remercions de l'intérêt que vous portez à {nom_entreprise} et vous souhaitons bonne chance dans vos recherches.\n\nCordialement,\nL'équipe {nom_entreprise}"),
        ),
    ]
