# Generated by Django 5.2.12 on 2026-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_candidaturespontanee'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturespontanee',
            name='diplome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidaturespontanee',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidaturespontanee',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
