# Generated by Django 5.2.12 on 2026-05-29 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_candidaturespontanee_diplome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='jobs.questionnaire'),
        ),
        migrations.CreateModel(
            name='QuestionQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('type_question', models.CharField(choices=[('COURT', 'Réponse courte'), ('LONG', 'Réponse longue'), ('NUMERIQUE', 'Numérique'), ('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple')], default='COURT', max_length=20)),
                ('requis', models.BooleanField(default=False)),
                ('disqualifiant', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.questionnaire')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseChoix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='jobs.questionquestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField(blank=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='jobs.candidature')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.questionquestionnaire')),
            ],
            options={
                'unique_together': {('candidature', 'question')},
            },
        ),
    ]
