# Generated by Django 5.2.12 on 2026-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_questionnaire_offreemploi_questionnaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetierReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('secteur', models.CharField(max_length=100)),
                ('niveau_experience', models.CharField(blank=True, max_length=50)),
                ('mots_cles', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['secteur', 'titre'],
            },
        ),
    ]
