# Generated by Django 5.2.12 on 2026-05-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_metierreferentiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='profil_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
