# Generated by Django 5.2.12 on 2026-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_candidature_profil_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé de profil / Bio'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Lien GitHub'),
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn'),
        ),
    ]
