# Generated by Django 5.2.12 on 2026-06-11 17:50

import django.core.validators
import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_profilcandidat_bio_profilcandidat_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv_rapide',
            field=models.FileField(blank=True, null=True, upload_to='cv_rapide/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), jobs.validators.validate_document_mime, jobs.validators.validate_file_size(5)]),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation_file',
            field=models.FileField(blank=True, null=True, upload_to='lettres_motivation/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), jobs.validators.validate_document_mime, jobs.validators.validate_file_size(5)], verbose_name='Lettre de motivation (Fichier)'),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), jobs.validators.validate_document_mime, jobs.validators.validate_file_size(5)]),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', validators=[jobs.validators.validate_image_mime, jobs.validators.validate_file_size(2)], verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_entreprises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(2)]),
        ),
    ]
