# Generated by Django 5.2.12 on 2026-06-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_add_file_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROUVER_OFFRE', 'Approuver offre'), ('REFUSER_OFFRE', 'Refuser offre'), ('APPROUVER_ENTREPRISE', 'Approuver entreprise'), ('REFUSER_ENTREPRISE', 'Refuser entreprise'), ('SUPPRIMER_USER', 'Supprimer utilisateur'), ('SUPPRIMER_OFFRE', 'Supprimer offre'), ('AUTRE', 'Autre')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
