# Generated by Django 5.2.12 on 2026-06-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_add_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeActivationPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_paiement', models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='CIB', max_length=20)),
                ('est_traitee', models.BooleanField(default=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_premium', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
