# Generated by Django 5.2.12 on 2026-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_demandeactivationpremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeactivationpremium',
            name='nb_mois',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profilentreprise',
            name='premium_expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium expire le'),
        ),
    ]
