# Generated by Django 5.2.12 on 2026-06-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_demandeactivationpremium_nb_mois_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeactivationpremium',
            name='moyen_paiement',
            field=models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA'), ('CHARGILY', 'Chargily Pay')], default='CIB', max_length=20),
        ),
        migrations.CreateModel(
            name='InvitationEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('UTILISATEUR', 'Utilisateur'), ('INVITE', 'Invité')], default='UTILISATEUR', max_length=20)),
                ('expire_at', models.DateTimeField()),
                ('est_acceptee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_equipe', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('ADMIN', 'Administrateur'), ('UTILISATEUR', 'Utilisateur'), ('INVITE', 'Invité')], default='UTILISATEUR', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='jobs.profilentreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre_equipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_ajout'],
                'unique_together': {('entreprise', 'user')},
            },
        ),
    ]
