# Generated by Django 5.2.12 on 2026-06-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_equipe_membres_invitations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('CREER_OFFRE', 'Créer offre'), ('MODIFIER_OFFRE', 'Modifier offre'), ('CLOTURER_OFFRE', 'Clôturer offre'), ('STATUT_CANDIDATURE', 'Changer statut candidature'), ('EVALUER_CANDIDATURE', 'Évaluer candidature'), ('INVITER_MEMBRE', 'Inviter membre'), ('RETIRER_MEMBRE', 'Retirer membre'), ('CHANGER_ROLE', 'Changer rôle membre'), ('AUTRE', 'Autre')], max_length=25)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_logs', to='jobs.profilentreprise')),
                ('membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
