# Generated by Django 5.2.12 on 2026-06-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_add_slug_to_profil_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration automatique"),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug URL'),
        ),
    ]
