# Generated by Django 5.2.12 on 2026-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_offreemploi_date_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecandidat',
            name='secteur',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('BANQUE', 'Métiers Banque et Assurances'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True, verbose_name="Secteur d'activité"),
        ),
    ]
