# Generated by Django 5.2.12 on 2026-07-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_profilentreprise_linkedin_site_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationcandidat',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
