# Generated by Django 5.2.12 on 2026-07-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_alter_formationcandidat_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationcandidat',
            name='etablissement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Université ou École'),
        ),
    ]
