# Generated by Django 5.2.12 on 2026-07-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_alter_formationcandidat_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
    ]
