# Generated by Django 5.2.12 on 2026-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_profilcandidat_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='adresse_complete',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse complète (pour la carte)'),
        ),
        migrations.AlterField(
            model_name='experiencecandidat',
            name='secteur',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='specialite',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True, verbose_name='Spécialité / Secteur'),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='secteur_souhaite',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='specialite',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, null=True, verbose_name='Spécialité / Secteur'),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='secteur_activite',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial, Technico Commercial, Service Client'), ('PRODUCTION', 'Production, Méthode, Industrie'), ('FINANCE', 'Comptabilité, Finance'), ('LOGISTIQUE', 'Logistique, Achat, Stock, Transport'), ('MARKETING', 'Marketing, Communication'), ('IT', "Informatique, Systèmes d'Information, Internet"), ('BTP', 'Chantier, Métiers BTP, Architecture'), ('ADMIN', 'Administration, Moyens Généraux'), ('VENTE', 'Vente, Télévente, Assistanat'), ('SANTE', 'Santé, Médical, Pharmacie'), ('INGENIERIE', 'Ingénierie, Etudes, Projet, R&D'), ('RH', 'RH, Personnel, Formation'), ('AUTRE', 'Autre'), ('SECRETARIAT', 'Assistanat, Secrétariat'), ('QSE', 'Qualité, Sécurité, Environnement'), ('TOURISME', 'Hôtellerie, Tourisme, Restauration, Loisirs'), ('MAINTENANCE', 'Maintenance, Entretien'), ('JURIDIQUE', 'Juridique, Fiscal, Audit, Conseil'), ('GRANDS_COMPTES', 'Responsable Commercial, Grands Comptes')], max_length=100, verbose_name="Secteur d'activité"),
        ),
    ]
