# Generated by Django 5.2.12 on 2026-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_profilentreprise_adresse_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='nombre_postes',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de postes à pourvoir'),
        ),
    ]
