# Generated by Django 5.2.12 on 2026-07-17 12:19

import django.core.validators
import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_offreemploi_nombre_postes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaturespontanee',
            name='cv',
            field=models.FileField(upload_to='cvs_spontanes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), jobs.validators.validate_document_mime, jobs.validators.validate_file_size(5)]),
        ),
    ]
