# Generated by Django 5.2.16 on 2026-07-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_alter_candidaturespontanee_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='metierreferentiel',
            options={'ordering': ['secteur_code', 'titre']},
        ),
        migrations.RemoveField(
            model_name='metierreferentiel',
            name='mots_cles',
        ),
        migrations.RemoveField(
            model_name='metierreferentiel',
            name='niveau_experience',
        ),
        migrations.RemoveField(
            model_name='metierreferentiel',
            name='secteur',
        ),
        migrations.AddField(
            model_name='metierreferentiel',
            name='code_fiche',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='metierreferentiel',
            name='fiche_metier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='metierreferentiel',
            name='secteur_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='experiencecandidat',
            name='secteur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Domaine d'activité (code ANEM)"),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité (code Domaine ANEM)'),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='secteur_souhaite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine souhaité (code ANEM)'),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité (code Domaine ANEM)'),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='secteur_activite',
            field=models.CharField(choices=[('A', 'Agriculture et pêche'), ('B', 'Énergie, extraction et hydrocarbure'), ('C', 'Industrie'), ('D', 'Installation, maintenance et propreté'), ('E', "Artisanat d'art"), ('F', 'Bâtiment et travaux publics'), ('G', 'Commerce'), ('H', 'Hôtellerie, restauration et tourisme'), ('I', 'Transport et logistique'), ('J', 'Communication, média et multimédia'), ('K', 'Banque, assurances et immobilier'), ('L', "Support à l'entreprise"), ('M', 'Santé'), ('N', 'Spectacle'), ('O', 'Formation, enseignement et recherche scientifique'), ('P', 'Services à la personne et à la collectivité')], max_length=100, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='metierreferentiel',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metiers', to='jobs.domaine'),
        ),
        migrations.AddField(
            model_name='domaine',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='jobs.secteur'),
        ),
        migrations.CreateModel(
            name='SousDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_domaines', to='jobs.domaine')),
            ],
        ),
        migrations.AddField(
            model_name='metierreferentiel',
            name='sous_domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metiers', to='jobs.sousdomaine'),
        ),
    ]
