# Generated by Django 5.2.16 on 2026-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_domaine_secteur_alter_metierreferentiel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='cv_pdf_maj_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour du CV'),
        ),
    ]
