# Generated by Django 5.2.16 on 2026-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0055_profilcandidat_cv_pdf_maj_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('RECUE', '🟡 Candidature reçue'), ('EN_COURS', '🔵 En cours d’étude'), ('PRESELECTION', '🟣 Présélectionné'), ('ENTRETIEN', '🟠 Entretien programmé'), ('RETENU', '🟢 Candidat retenu'), ('REFUSE', '🔴 Candidat refusé')], default='RECUE', max_length=20),
        ),
    ]
