# Generated by Django 5.2.16 on 2026-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_alter_candidature_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='competences',
            field=models.TextField(blank=True, null=True, verbose_name='Compétences requises'),
        ),
    ]
