# Generated by Django 5.2.16 on 2026-08-19 12:37

import django.core.validators
import django.db.models.deletion
import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_offreemploi_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to='bannieres_entreprises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(5)], verbose_name='Bannière (page vitrine)'),
        ),
        migrations.AddField(
            model_name='profilentreprise',
            name='culture_entreprise',
            field=models.TextField(blank=True, null=True, verbose_name="Culture d'entreprise"),
        ),
        migrations.CreateModel(
            name='EntreprisePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_entreprises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(3)])),
                ('legende', models.CharField(blank=True, max_length=150, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
