# Generated by Django 5.2.16 on 2026-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0058_profilentreprise_banniere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='code_public',
            field=models.CharField(blank=True, help_text="Code court aléatoire utilisé dans l'URL publique de l'offre, généré automatiquement.", max_length=8, null=True, unique=True, verbose_name='Code public (URL SEO)'),
        ),
    ]
