# Generated by Django 5.2.17 on 2026-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0060_backfill_code_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('Mail', 'Mail'), ('Download', 'Download'), ('SlidersHorizontal', 'SlidersHorizontal'), ('Sparkles', 'Sparkles'), ('Heart', 'Heart'), ('Headset', 'Headset'), ('Star', 'Star'), ('Shield', 'Shield'), ('Zap', 'Zap'), ('Clock', 'Clock'), ('CheckCircle2', 'CheckCircle2'), ('CreditCard', 'CreditCard'), ('Users', 'Users'), ('TrendingUp', 'TrendingUp'), ('Search', 'Search'), ('FileText', 'FileText'), ('Award', 'Award'), ('Target', 'Target'), ('Lock', 'Lock'), ('Bell', 'Bell')], max_length=40, verbose_name='Icône')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_mois', models.PositiveIntegerField(unique=True, verbose_name='Durée (mois)')),
                ('label', models.CharField(max_length=50, verbose_name='Libellé')),
                ('prix_da', models.PositiveIntegerField(verbose_name='Prix final (DA)')),
                ('populaire', models.BooleanField(default=False, verbose_name='Badge "Populaire"')),
                ('actif', models.BooleanField(default=True, verbose_name='Visible/activable')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'ordering': ['ordre', 'nb_mois'],
            },
        ),
    ]
