# Generated by Django 5.2.17 on 2026-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0062_backfill_premium_plans_avantages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('GENERAL', 'Général (page Contact)'), ('RECRUTEUR', 'Recruteur (landing)'), ('PREMIUM', 'Premium')], max_length=20, verbose_name='Catégorie')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'ordering': ['categorie', 'ordre'],
            },
        ),
    ]
