# Generated by Django 5.2.17 on 2026-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0064_backfill_faq_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Compétence')),
                ('actif', models.BooleanField(default=True, verbose_name='Suggérée')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
