# Generated by Django 5.2.17 on 2026-08-20 12:47

import django.core.validators
import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0067_articlecategorie_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanniereAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bannieres_accueil/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(5)])),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('lien_url', models.URLField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SiteAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('lien_url', models.URLField(blank=True, null=True)),
                ('lien_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Libellé du lien')),
                ('type_annonce', models.CharField(choices=[('INFO', 'Info (bleu)'), ('WARNING', 'Avertissement (ambre)'), ('SUCCESS', 'Succès (vert)')], default='INFO', max_length=10)),
                ('actif', models.BooleanField(default=False)),
            ],
        ),
    ]
