# Generated by Django 5.2.17 on 2026-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0068_banniereaccueil_siteannonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu_html', models.TextField()),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
    ]
