# Generated by Django 5.2.17 on 2026-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0070_seed_pages_statiques'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GROQ', 'Groq (cloud)'), ('OLLAMA', 'Ollama (local, post-déploiement)')], default='GROQ', max_length=10)),
                ('groq_model', models.CharField(default='openai/gpt-oss-20b', max_length=100, verbose_name='Modèle Groq')),
                ('ollama_model', models.CharField(blank=True, default='mistral', max_length=100, verbose_name='Modèle Ollama')),
                ('temperature', models.FloatField(default=0.7)),
                ('reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('parser_cv_actif', models.BooleanField(default=True, verbose_name='Parser CV actif')),
                ('parser_cv_max_tokens', models.PositiveIntegerField(default=6000)),
                ('analyse_carriere_actif', models.BooleanField(default=True, verbose_name='Analyse carrière candidat active')),
                ('analyse_carriere_max_tokens', models.PositiveIntegerField(default=1200)),
                ('analyse_recruteur_actif', models.BooleanField(default=True, verbose_name='Analyse IA recruteur active')),
                ('analyse_recruteur_max_tokens', models.PositiveIntegerField(default=400)),
                ('generation_offre_actif', models.BooleanField(default=True, verbose_name="Génération d'offre IA active")),
                ('generation_offre_max_tokens', models.PositiveIntegerField(default=1600)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
