# Generated by Django 5.2.17 on 2026-08-20 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0072_alter_aiconfig_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='analyse_carriere_max_tokens',
            field=models.PositiveIntegerField(default=1200, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='analyse_recruteur_max_tokens',
            field=models.PositiveIntegerField(default=400, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='generation_offre_max_tokens',
            field=models.PositiveIntegerField(default=1600, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='parser_cv_max_tokens',
            field=models.PositiveIntegerField(default=6000, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='nb_mois',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (mois)'),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='prix_da',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix final (DA)'),
        ),
    ]
