# Generated by Django 5.2.17 on 2026-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0073_alter_aiconfig_analyse_carriere_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='analyse_carriere_prompt',
            field=models.TextField(blank=True, help_text='Instructions système (aucune variable à interpoler — le profil du candidat est envoyé séparément). Si vide, le prompt par défaut du code est utilisé.', verbose_name='Prompt Analyse carrière'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='analyse_recruteur_prompt',
            field=models.TextField(blank=True, help_text='Variables disponibles : {offre_titre}, {entreprise}, {specialite}, {type_contrat}, {wilaya}, {nom_candidat}, {titre_candidat}, {diplome}, {competences}, {experiences}, {formations}, {score}. Si vide, le prompt par défaut du code est utilisé.', verbose_name='Prompt Analyse recruteur'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='generation_offre_prompt',
            field=models.TextField(blank=True, help_text='Variables disponibles : {titre}, {specialite}, {diplome}, {experience}, {contrat}, {wilaya}. Si vide, le prompt par défaut du code est utilisé.', verbose_name="Prompt Génération d'offre"),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='parser_cv_prompt',
            field=models.TextField(blank=True, help_text='Variables obligatoires : {cv_text} et {domaines_list}. Si vide, le prompt par défaut du code est utilisé.', verbose_name='Prompt Parser CV'),
        ),
    ]
