# Generated by Django 5.2.17 on 2026-08-21 12:21

import django.core.validators
import django.db.models.deletion
import jobs.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0075_backfill_aiconfig_prompts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_min_reservation_heures', models.PositiveIntegerField(default=24, help_text='Ex: 24 = un candidat ne peut pas réserver un créneau dans les 24h à venir.', verbose_name='Délai minimum avant un RDV (heures)')),
                ('horizon_max_jours', models.PositiveIntegerField(default=30, help_text='Un candidat ne peut pas réserver au-delà de cet horizon.', verbose_name='Horizon maximum de réservation (jours)')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_creneau_minutes', models.PositiveIntegerField(default=30)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='JourBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Type de document')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.AddField(
            model_name='alerteemploi',
            name='derniere_consultation',
            field=models.DateTimeField(blank=True, help_text='Mise à jour quand le candidat consulte les offres de cette alerte — sert à calculer le compteur "nouvelles offres".', null=True, verbose_name='Dernière consultation'),
        ),
        migrations.CreateModel(
            name='ActiviteProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('CANDIDATURE_CONSULTEE', 'Candidature consultée'), ('PROFIL_RECOMMANDE', 'Profil recommandé (score élevé)')], max_length=25)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_profil', to=settings.AUTH_USER_MODEL)),
                ('candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jobs.candidature')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=300, verbose_name='Motif de la demande')),
                ('statut', models.CharField(choices=[('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé'), ('ABSENT', 'Absent')], default='CONFIRME', max_length=10)),
                ('notes_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personnalise', models.CharField(blank=True, max_length=150, verbose_name='Nom (ex: CV version IT)')),
                ('fichier', models.FileField(upload_to='documents_candidats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), jobs.validators.validate_document_mime, jobs.validators.validate_file_size(5)])),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.profilcandidat')),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='jobs.typedocument')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Compétence')),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('CONFIRME', 'Confirmé / Expert')], default='DEBUTANT', max_length=20)),
                ('source', models.CharField(choices=[('DECLARE', 'Auto-déclaré'), ('TESTE', 'Vérifié par test')], default='DECLARE', max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_detail', to='jobs.profilcandidat')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('profil', 'label')},
            },
        ),
    ]
