# Generated by Django 5.2.17 on 2026-08-21 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0077_seed_types_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='conseils_dashboard_actif',
            field=models.BooleanField(default=True, verbose_name='Conseils personnalisés (tableau de bord) actifs'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='conseils_dashboard_max_tokens',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='conseils_dashboard_prompt',
            field=models.TextField(blank=True, help_text='Instructions système (le profil/score/activité du candidat sont envoyés séparément). Si vide, le prompt par défaut du code est utilisé.', verbose_name='Prompt Conseils personnalisés'),
        ),
    ]
