# Generated by Django 5.2.17 on 2026-08-22 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0078_aiconfig_conseils_dashboard_actif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True, verbose_name='Palier')),
                ('prix_mensuel_da', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix mensuel (DA)')),
                ('prix_annuel_da', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix annuel (DA)')),
                ('remise_annuelle_active', models.BooleanField(default=False, verbose_name='Remise annuelle affichée')),
                ('limite_offres', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limite offres actives (vide = illimité)')),
                ('limite_cv_mois', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limite téléchargements CV/mois (vide = illimité)')),
                ('acces_coordonnees', models.BooleanField(default=False, verbose_name='Coordonnées candidats visibles')),
                ('acces_ia_recommandes', models.BooleanField(default=False, verbose_name='Candidats recommandés (IA)')),
                ('acces_ia_avancee', models.BooleanField(default=False, verbose_name='Recherche/filtres/stats IA avancés')),
                ('acces_equipe', models.BooleanField(default=False, verbose_name="Gestion d'équipe multi-utilisateurs")),
                ('support_label', models.CharField(blank=True, max_length=100, verbose_name='Support (texte libre)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Visible/achetable')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expire le (vide = illimité)')),
                ('renouvellement_auto', models.BooleanField(default=True)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='jobs.profilentreprise')),
                ('palier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='jobs.palier')),
            ],
        ),
    ]
