# Generated by Django 5.2.17 on 2026-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0080_seed_paliers_migrer_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='mise_en_avant_accueil',
            field=models.BooleanField(default=False, verbose_name='Afficher dans "Ils nous font confiance" (logos clients)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='categorie',
            field=models.CharField(choices=[('GENERAL', 'Général (page Contact)'), ('RECRUTEUR', 'Recruteur (landing)'), ('PREMIUM', 'Premium'), ('PALIERS', 'Paliers (page Abonnements)')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
