# Generated by Django 5.2.17 on 2026-08-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0083_telechargementcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionsLegalesEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, default='TafTech', max_length=200)),
                ('registre_commerce', models.CharField(blank=True, max_length=50)),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('tva', models.CharField(blank=True, max_length=50, verbose_name='N° TVA (le cas échéant)')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palier_nom', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('montant_da', models.PositiveIntegerField()),
                ('periode', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=10)),
                ('moyen_paiement', models.CharField(blank=True, max_length=50)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('numero_facture', models.CharField(editable=False, max_length=30, unique=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
