# Generated by Django 5.2.17 on 2026-08-23 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0084_mentionslegalesentreprise_paiementabonnement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='source',
            field=models.CharField(choices=[('SITE', 'Site TafTech'), ('CVTHEQUE', 'Invitation CVthèque'), ('AUTRE', 'Autre')], default='SITE', max_length=20, verbose_name='Source de la candidature'),
        ),
        migrations.CreateModel(
            name='RechercheSauvegardee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la recherche')),
                ('filtres', models.JSONField(default=dict, verbose_name='Filtres (query params CVthèque)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_sauvegardees', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InvitationCVTheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_cvtheque', to='jobs.profilentreprise')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='jobs.offreemploi')),
            ],
            options={
                'unique_together': {('entreprise', 'candidat', 'offre')},
            },
        ),
    ]
