# Generated by Django 5.2.17 on 2026-08-23 10:47

from django.db import migrations


def seed_page(apps, schema_editor):
    PageStatique = apps.get_model('jobs', 'PageStatique')
    PageStatique.objects.get_or_create(
        slug='formation-recruteur',
        defaults={
            'titre': 'Formation recruteur',
            'contenu_html': '<p>Cette section sera bientôt enrichie de guides et de bonnes pratiques pour tirer le meilleur parti de TafTech. En attendant, contactez-nous à taftech963@gmail.com pour toute question.</p>',
        },
    )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0085_candidature_source_recherchesauvegardee_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_page, reverse_noop),
    ]
