# Generated by Django 5.2.17 on 2026-08-25 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0086_seed_page_formation_recruteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilentreprise',
            name='annee_creation',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name="Année de création de l'entreprise"),
        ),
    ]
