# Generated by Django 5.2.17 on 2026-08-25 20:56

import django.core.validators
import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0087_profilentreprise_annee_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(3)]),
        ),
        migrations.AlterField(
            model_name='banniereaccueil',
            name='image',
            field=models.ImageField(upload_to='bannieres_accueil/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(5)]),
        ),
        migrations.AlterField(
            model_name='entreprisephoto',
            name='image',
            field=models.ImageField(upload_to='photos_entreprises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(3)]),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to='bannieres_entreprises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(5)], verbose_name='Bannière (page vitrine)'),
        ),
        migrations.AlterField(
            model_name='profilentreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_entreprises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'png', 'webp']), jobs.validators.validate_image_mime, jobs.validators.validate_file_size(2)]),
        ),
    ]
