# Generated by Django 5.2.17 on 2026-08-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0088_alter_article_image_couverture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
    ]
