# Generated by Django 5.2.17 on 2026-08-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0090_backfill_abonnement_avant_suppression_premium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumAvantage',
        ),
        migrations.DeleteModel(
            name='PremiumPlan',
        ),
        migrations.RemoveField(
            model_name='profilentreprise',
            name='est_premium',
        ),
        migrations.RemoveField(
            model_name='profilentreprise',
            name='premium_expire_at',
        ),
    ]
