# Generated by Django 5.2.17 on 2026-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0091_supprime_premium_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('INFO', 'Information'), ('ENTRETIEN', 'Entretien programmé'), ('RETENU', 'Candidature retenue'), ('REFUS', 'Candidature refusée'), ('ALERTE', 'Alerte Emploi'), ('CANDIDATURE_SPONTANEE', 'Candidature spontanée reçue'), ('NOUVELLE_CANDIDATURE', 'Nouvelle candidature'), ('CANDIDAT_RECOMMANDE', 'Candidat recommandé')], default='INFO', max_length=25),
        ),
    ]
