# Generated by Django 5.2.17 on 2026-08-29 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0095_palier_remove_limite_cv_mois'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du pack')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_da', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix (DA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Visible/achetable')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='abonnemententreprise',
            name='credits_achetes_restants',
            field=models.PositiveIntegerField(default=0, verbose_name='Crédits CVthèque achetés restants'),
        ),
        migrations.CreateModel(
            name='PaiementCreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_nom', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField()),
                ('montant_da', models.PositiveIntegerField()),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('numero_facture', models.CharField(editable=False, max_length=30, unique=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_credit_pack', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='AccesCandidatDebloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MENSUEL', 'Quota mensuel du palier'), ('ACHETE', 'Pack de crédits acheté')], max_length=10)),
                ('date_debloque', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debloque_par', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats_debloques', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_debloque'],
                'unique_together': {('entreprise', 'candidat')},
            },
        ),
    ]
