# Generated by Django 5.2.17 on 2026-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0096_credits_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipeactionlog',
            name='action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('CREER_OFFRE', 'Créer offre'), ('MODIFIER_OFFRE', 'Modifier offre'), ('CLOTURER_OFFRE', 'Clôturer offre'), ('STATUT_CANDIDATURE', 'Changer statut candidature'), ('EVALUER_CANDIDATURE', 'Évaluer candidature'), ('INVITER_MEMBRE', 'Inviter membre'), ('RETIRER_MEMBRE', 'Retirer membre'), ('CHANGER_ROLE', 'Changer rôle membre'), ('DEBLOQUER_CANDIDAT', 'Débloquer candidat CVthèque'), ('AUTRE', 'Autre')], max_length=25),
        ),
    ]
