# Generated by Django 5.2.17 on 2026-09-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0099_profilcandidat_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='visible_cvtheque',
            field=models.BooleanField(default=True, help_text="Si désactivé, le profil reste visible/recherchable mais aucun recruteur ne peut débloquer les coordonnées/CV via un crédit tant que ce n'est pas réactivé.", verbose_name='Profil déblocable dans la CVthèque'),
        ),
        migrations.CreateModel(
            name='PartageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='jobs.documentcandidat')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_partages', to='jobs.profilentreprise')),
            ],
            options={
                'ordering': ['-date_partage'],
                'unique_together': {('document', 'entreprise')},
            },
        ),
    ]
