# Generated by Django 5.2.17 on 2026-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0100_profilcandidat_visible_cvtheque_partagedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencereferentiel',
            name='synonymes',
            field=models.TextField(blank=True, default='', help_text="Intitulés équivalents séparés par des virgules (ex: Project Management, Gestion des projets) — utilisés pour normaliser les compétences extraites d'un CV vers ce libellé.", verbose_name='Synonymes / traductions'),
        ),
    ]
