# Generated by Django 5.2.17 on 2026-09-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0101_competence_referentiel_synonymes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Compétence')),
                ('type_exigence', models.CharField(choices=[('OBLIGATOIRE', 'Obligatoire'), ('SOUHAITEE', 'Souhaitée')], default='OBLIGATOIRE', max_length=15)),
                ('niveau_requis', models.CharField(blank=True, choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('CONFIRME', 'Confirmé / Expert')], max_length=20, null=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_requises', to='jobs.offreemploi')),
            ],
            options={
                'ordering': ['type_exigence', 'label'],
                'unique_together': {('offre', 'label')},
            },
        ),
    ]
