# Generated by Django 5.2.17 on 2026-09-06 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0102_competenceoffre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='generation_offre_max_tokens',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
