# Generated by Django 5.2.12 on 2026-05-08 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_code_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(help_text="Résumé de l'erreur")),
                ('details', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('user_agent', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'Erreur Système",
                'verbose_name_plural': "Logs d'Erreurs Système",
                'ordering': ['-timestamp'],
            },
        ),
    ]
