# Generated by Django 5.2.12 on 2026-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_systemerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_verification_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
