# Generated by Django 5.2.12 on 2026-06-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_login_lockout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='est_compte_google',
            field=models.BooleanField(default=False),
        ),
    ]
