# Generated by Django 5.2.12 on 2026-07-12 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_est_compte_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nin',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{18}$', 'Le NIN doit contenir exactement 18 chiffres.')], verbose_name="Numéro d'Identification National"),
        ),
    ]
