# Generated by Django 5.2.12 on 2026-07-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consentement_cvtheque',
            field=models.BooleanField(default=False, verbose_name='Consentement traitement des données candidats (CVthèque)'),
        ),
    ]
