# Generated by Django 5.2.12 on 2026-07-17 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_consentement_cvtheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,14}$', 'Numéro de téléphone invalide (8 à 14 chiffres, + optionnel en préfixe).')]),
        ),
    ]
