# Generated by Django 5.2.17 on 2026-08-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intitule_poste',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Intitulé de poste (recruteur, cosmétique)'),
        ),
    ]
