from .notifications import (
    NotificationListAPIView,
    MarkNotificationReadAPIView,
    PublicStatsAPIView,
    StatsGeoAPIView,
    EntrepriseListAPIView,
    EntrepriseDetailAPIView,
)
from .offres import (
    JobListAPIView,
    JobDetailAPIView,
    JobCreateAPIView,
    UpdateOffreRecruteurAPIView,
    CloturerOffreAPIView,
    ConstantsAPIView,
)
from .profils import (
    ProfilCandidatAPIView,
    ExperienceAPIView,
    ExperienceDetailAPIView,
    FormationAPIView,
    FormationDetailAPIView,
    OffreSauvegardeeListCreateAPIView,
    OffreSauvegardeeDeleteAPIView,
    AlerteEmploiListCreateAPIView,
    AlerteEmploiDetailAPIView,
    ParametresNotificationsAPIView,
)
from .candidatures import (
    PostulerAPIView,
    PostulerRapideAPIView,
    MesCandidaturesAPIView,
    UpdateCandidatureStatusAPIView,
    DeleteCandidatureAPIView,
    EvaluerCandidatureAPIView,
    Top5CandidatsAPIView,
)
from .recruteur import (
    DashboardRecruteurAPIView,
    UpdateProfilEntrepriseAPIView,
    ParametresRecruteurAPIView,
    CVThequeView,
    ToggleFavoriCVAPIView,
    EnvoyerCandidatureSpontaneeAPIView,
    ListeCandidaturesSpontaneesAPIView,
    MarquerSpontaneeLueAPIView,
    SupprimerSpontaneeAPIView,
    QuestionnaireListCreateAPIView,
    QuestionnaireDetailAPIView,
    DemanderActivationPremiumAPIView,
    EnvoyerRecuPremiumAPIView,
    ChargilyCheckoutAPIView,
    ChargilyWebhookAPIView,
)
from .admin import (
    AdminPagination,
    AdminOffresListAPIView,
    AdminOffreModerateAPIView,
    AdminEntreprisesListAPIView,
    AdminEntrepriseModerateAPIView,
    AdminStatsAPIView,
    AdminUsersListAPIView,
    AdminUserModerateAPIView,
    AdminBroadcastEmailAPIView,
    AdminCandidaturesListAPIView,
    ExportCandidaturesCSVAPIView,
    ExportEntreprisesCSVAPIView,
    ExportOffresCSVAPIView,
    ExportUtilisateursCSVAPIView,
    AdminMarcheAPIView,
    AdminAuditLogAPIView,
    AdminDemandesPremiumAPIView,
    AdminCompteAdminsAPIView,
)
from .ia import (
    OffresRecommandeesAPIView,
    ParserCVAPIView,
    MetierReferentielAPIView,
    MetierReferentielAdminAPIView,
    SuggestionsCarriereAPIView,
    AnalyseCarriereGroqAPIView,
    AnalyseGroqRecruteurAPIView,
    GenererOffreIAAPIView,
)
from .bulletin import GenererBulletinPDFAPIView
from .equipe import (
    EquipeAPIView,
    InviterMembreAPIView,
    AccepterInvitationAPIView,
    EquipeAuditLogAPIView,
)